### ISSUE TITLE
Ability to set Entity ID and get Entity by ID

### ISSUE THREAD

**Issue by CompuIves** [libgdx/ashley#115]
As the title says, add the ability to get an Entity by ID and/or set the Entity ID. It would be a lot easier when using Entities for a networked game since the server can just send the entity ID with the changes and the client can apply them. 
It would be a lot easier writing packets when you know the ID's between the entities from the server and the client are synchronized.

**Comment by alex-place** [comment]
Any suggestions on syncing entities over the network if not by id? At the moment I'm just using an ID component instead that tries to imitate that behavior. A setID while being dangerous would be beneficial if just for networked games.

**Comment by saltares** [comment]
I think `setId()` is, indeed, way to dangerous. Why don't you open a new issue with your requirements for a networked entity system? Maybe we can discuss better over there.
