### ISSUE TITLE
Component add or remove not possible in EntityListener methods

### ISSUE THREAD

**Issue by acatinon** [libgdx/ashley#122]
I have a class implementing `EntityListener`, and I try to add a component to an entity in `entityRemoved()` method.

The component is never added. Because `entityRemoved()` is called by `processComponentOperations()`. When I add a component to an entity, a new `ComponentOperation` is added to `componentOperations` but is never processed because the `numOperations` is not updated. And at the end of `processComponentOperations()`, `componentOperations` is cleared.

**Comment by siondream** [comment]
Found the problem [here](https://github.com/libgdx/ashley/blob/master/ashley/src/com/badlogic/ashley/core/Engine.java#L391)

```java
	private void processComponentOperations () {
		int numOperations = componentOperations.size;

		for (int i = 0; i < numOperations; ++i) {
			ComponentOperation operation = componentOperations.get(i);

			switch (operation.type) {
			case Add:
				operation.entity.addInternal(operation.component);
				break;
			case Remove:
				operation.entity.removeInternal(operation.componentClass);
				break;
			}

			componentOperationsPool.free(operation);
		}

		componentOperations.clear();
	}
```

The size of the `componentOperations` array changes while iterating so we need to use `componentOperations.size` in the loop rather than caching it off.

Will fix ASAP.
