### ISSUE TITLE
A few questions/suggestions

### ISSUE THREAD

**Issue by RedDogVG** [libgdx/ashley#123]
I always had the same problem with entities frameworks. The concept of component is in the data, not the behaviour. This causes some problems to my opinion.

First I had to remember an awful lot of combinations to add what I wanted: "lets see... I want it to jump, so I need to add a position, a velocity, rigid body to check for the floor, keyboard events, etc...". My memory is not that good, I always end up with a cheat sheet and a lot of indirect work.

Second I end up with a lot of tags/markers types of components, with that I meant components with no data whatsoever that are there only to inform of a behaviour for a system to pick it up. For example I want the character to fly but that requires only position and velocity, the same requirements of the normal movement; so I end up creating a fly component, because I need to mark a different type of movement with the same requirements but different logic.

My vision/approach is a behaviour based component framework. It's almost the same concept, data and logic are separated, the only difference is that the component is the behaviour I want the entity to have and not the data that supports the logic of that behaviour.
The components would be something similar to your idea of families, tags for behaviours (not logic).
For example I add a jumping component, a flying one and remove the walking type. The idea is adding the tags/markers only and letting the framework manage the data in the background automatically. Some data may need initialization (like a sprite), some may be ok with the defaults (like velocity in a lot of cases).

By no means I have the best knowledge of how to create a perfect component framework. This is just my experience with my own component framework created in AS3.
It is a lot faster and more intuitive to code with what you want the entity to do, instead of what it has and then, what it has determines what it does.

Thanks

**Comment by siondream** [comment]
* Updating systems at different rates: you can already do that with [`IntervalSystem`](https://github.com/libgdx/ashley/wiki/Built-in-Entity-Systems#intervalsystem).
* Delta time basically refers to the difference in time between two frames. Ashley takes the delta time as a parameter through the update method, it's up to you to supply a constant number or not.
* The approach you suggest is more on the lines of what Unity does, but that has quite a few flaws of its own.

We're definitely not gonna break Ashley apart at this point in time and change our approach. I think the framework is fairly stable at the moment, and we don't want to break the API for everyone else.

**Comment by RedDogVG** [comment]
Now I saw the IntervalSystem, cool.
For some reason I thought that the engine took control of the game loop, sorry I didn't understood that I need to update it manually.

Mmm... For Unity everything is a component and there is no separation of data and logic. I think that you refer to the idea that each component should be self sufficient.

Of course breaking everything would be a bad idea, but how about adding new options?
Using families not only for classifying entities, but as way to add components.
For example "entity.AddFamily(Family);". If there is a component required for that family then it's left intact, if it needs a component (data) that is not present add it automatically in a default value.

That way it could keep the engine as it's but also add the possibility of working with a layer of abstraction, with behaviours instead of the data directly.
What do you think?

**Comment by siondream** [comment]
I refer to the idea that Components in Unity have both data and logic, we meant the same thing.

That's an interesting concept but it would pose some potential problems. I think users could just write a data driven layer on top of Ashley so it's easier to define entities from a json file maybe.
