### ISSUE TITLE
Make PooledEngine transparent

### ISSUE THREAD

**Issue by Nauktis** [libgdx/ashley#126]
It would be nice that Engine implements createEntity() like PooledEngine does so that the code can be agnostic of the type of engine it's using.

Even better would be that both Engine and PooledEngine implement a common interface.

**Comment by siondream** [comment]
`Engine` is already agnostic of the type of `Entity` you're using. You could just do:

```java
public class MyEntity extends Entity {};

Engine engine = new Engine();
engine.addEntity(new MyEntity());
```

At the moment you cannot have custom entities with `PooledEngine`, but like I mentioned on #127, I wouldn't know a use case for that.

Let's keep the discussion on the other issue.
