### ISSUE TITLE
Pool of the PooledEngine is fixed.

### ISSUE THREAD

**Issue by Nauktis** [libgdx/ashley#127]
Even though there is a generic Pool class, the PooledEngine uses a private EntityPool.
This makes it impossible to use a subclass of Entity as entity for the engine.

In order to make the framework more open, it would be nice to be able to provide any pool (of entities of course) to the PooledEngine.

**Comment by siondream** [comment]
What;s the use case for subclassing `Entity`? If you want special behaviour, you could probably achieve that through components and systems.

If there is a good case for it, I'm happy to allow the user to inject any entity pool.

**Comment by siondream** [comment]
It's been 22 days since this was opened. I guess if there was a proper use case/real interest for this, there would have been more activity on this issue. I will be closing this for now until that happens.
