### ISSUE TITLE
Nested iterators

### ISSUE THREAD

**Issue by sreich** [libgdx/ashley#131]
So I've recently encountered an issue that i've been pullng my hair out for for the past few hours, behavior seemed erratic, almost as if it was a threading issue.

Managed to boil it down to, in a system i'm essentially doing 
`
update()  { 

ImmutableArray<Entity> entities = engine.getEntitiesFor....
for (e: entities) {
 someMethod();
}
}
'
where somemethod does quite literally the same thing

Now, i've heard brief mention about some issues with nested iterators in libgdx, but i never paid attention to it. Is this exactly what I am running into? if so, how does one address it?

The behavior was quite odd, inside someMethod, despite asking for all entities that *must* have all of (component), it was returning like..every entity there was, and they didn't have the component i asked for. moving the block that was within somemethod(), outside of the overbearing for loop resolves the issue, though now i'd have to rethink to try to actually work around it.

thoughts? or am i just crazy, because it sure feels like it..i would've thought those things would never possibly collide :)

**Comment by siondream** [comment]
I assume `someMethod()` correctly gets the entity collection for the given family. Anyway, you cannot do nested iteration with the libgdx collections unless you allocate a new iterator, which you cannot do from `ImmutableArray`.

However, you can easily work around it.

```java
for (int i = 0; i < entities.size(); ++i) {
	Entity entity = entities.get(i);
	...
}
```

**Comment by sreich** [comment]
Okay thanks. Too bad it does not throw an exception. I've read online about the libgdx classes throwing exceptions on such events.

**Comment by sreich** [comment]
sorry to have to bother you again, but switching all iterators all over to traditional for-int loops, sadly i still get the same behavior :/

oddly this only occurs on item dropping, which is the place where i create several entities.

I should tell you that there is a client and server thread. both have their own data sets for everything and only access their own. (each has an m_world). However, the *one thing* that I do not do this for is Mappers, where I follow the given code for using static mappers. This just occurred to me, that they are static and are accessed in the same manner across threads.

I do not however understand how this could result in a family retrieval returning *all* of the entities (it seems), randomly, even ones you have not asked for. I can only trigger this behavior on item drops (after several), after which point the error could possibly happen anywhere there is a getEntitiesFor, I've seen it happen a few times in other regions.

I do use pooledengine, but the ctor is run as PooledEngine(2000, 2000, 2000, 2000), so this will never get hit. Upon trigger, there is no correlation between entity count and error rate either. I've seen it happen at 31, 27, 45...so i'm not hitting some other possible collection issue.

Do you think it is the Mappers being static (which i believe in java they would still be thread-global), and possibly anything involving them could have undefined behavior. Though still, only happens on several item creations...and i glanced at the inner code and could not see how such a case could even happen if this were causing undefined behavior.

       ImmutableArray<Entity> entities = m_world.engine.getEntitiesFor(Family.all(SpriteComponent.class, VelocityComponent.class).get());

                 for (int i = 0; i < entities.size(); ++i) {
                    simulate(entities.get(i), delta);
                  }

simulate {
       if (Mappers.control.get(entity) == null) {
                ItemComponent itemComponent = Mappers.item.get(entity);
                if (itemComponent != null && itemComponent.state == ItemComponent.State.DroppedInWorld) {
                    m_world.playerForId(1);
                }
    }
}

playerforID is as follows,

    public Entity playerForID(int playerIdWhoDropped) {
        assert !isClient();
        ImmutableArray<Entity> entities = engine.getEntitiesFor(Family.all(PlayerComponent.class).get());
        PlayerComponent playerComponent;
        for (int i = 0; i < entities.size(); ++i) {
            playerComponent = Mappers.player.get(entities.get(i));
            if (playerComponent.connectionId == playerIdWhoDropped) {
                return entities.get(i);
            }
        }
}

**Comment by sreich** [comment]
sorry to have to bother you again, but switching all iterators all over to traditional for-int loops, sadly i still get the same behavior :/

oddly this only occurs on item dropping, which is the place where i create several entities.

I should tell you that there is a client and server thread. both have their own data sets for everything and only access their own. (each has an m_world). However, the *one thing* that I do not do this for is Mappers, where I follow the given code for using static mappers. This just occurred to me, that they are static and are accessed in the same manner across threads.

I do not however understand how this could result in a family retrieval returning *all* of the entities (it seems), randomly, even ones you have not asked for. I can only trigger this behavior on item drops (after several), after which point the error could possibly happen anywhere there is a getEntitiesFor, I've seen it happen a few times in other regions.

I do use pooledengine, but the ctor is run as PooledEngine(2000, 2000, 2000, 2000), so this will never get hit. Upon trigger, there is no correlation between entity count and error rate either. I've seen it happen at 31, 27, 45...so i'm not hitting some other possible collection issue.

Do you think it is the Mappers being static (which i believe in java they would still be thread-global), and possibly anything involving them could have undefined behavior. Though still, only happens on several item creations...and i glanced at the inner code and could not see how such a case could even happen if this were causing undefined behavior.

       ImmutableArray<Entity> entities = m_world.engine.getEntitiesFor(Family.all(SpriteComponent.class, VelocityComponent.class).get());

                 for (int i = 0; i < entities.size(); ++i) {
                    simulate(entities.get(i), delta);
                  }

simulate {
       if (Mappers.control.get(entity) == null) {
                ItemComponent itemComponent = Mappers.item.get(entity);
                if (itemComponent != null && itemComponent.state == ItemComponent.State.DroppedInWorld) {
                    m_world.playerForId(1);
                }
    }
}

playerforID is as follows,

    public Entity playerForID(int playerIdWhoDropped) {
        assert !isClient();
        ImmutableArray<Entity> entities = engine.getEntitiesFor(Family.all(PlayerComponent.class).get());
        PlayerComponent playerComponent;
        for (int i = 0; i < entities.size(); ++i) {
            playerComponent = Mappers.player.get(entities.get(i));
            if (playerComponent.connectionId == playerIdWhoDropped) {
                return entities.get(i);
            }
        }
}

**Comment by sreich** [comment]
Further exploration made me uncover https://github.com/libgdx/ashley/pull/95

If this is indeed true, doesn't this mean that exactly what I am doing above is undefined, because simply because I'm attempting to retrieve entities from different threads, even if each thread maintains itself to its own data sets? 

If that is  true, that's not acceptable for my uses (and I suspect many others) . Multithreading is extremely common in multi-player games. Most every multiplayer game runs the client and server on the same system, even for single player games. It's usually done via threads, one for the client, one for the server. This would be rather unfortunate, as I've tried many very different entity systems in c++, never had any issues over there. 

Input would be appreciated, thanks.
