### ISSUE TITLE
Pooled engine createComponent() always returning a new component

### ISSUE THREAD

**Issue by viet54** [libgdx/ashley#132]
I create a new entity with engine.createEntity() then create a new component with engine.createComponent().  The component contains a boolean field isOld initialized to false.  I then add the component to the entity and add the entity to the engine.  Some logic runs and removes all the component from the entity and then removes the entity from the engine.  The component's reset() method gets called which sets its isOld to true.  When I call the engine.createComponent() again I get a component with isOld == false.  I'm sure that the component was already freed and should have been put back into the pool but it appears createComponent() is still returning a new component.  Am I missing something here?

I looked at the source and the ComponentPools class's constructor is setting the fields this.initialSize and this.maxSize to 0.  Shouldn't they be set to the constructor's argument and not 0?

**Comment by siondream** [comment]
Solved in PR #133, thanks again!
