### ISSUE TITLE
Family API (wiki)

### ISSUE THREAD

**Issue by luiz-pv9** [libgdx/ashley#144]
It seems that the API for Family has changed from the one described in the wiki:

```java
Family family = Family.all(PositionComponent.class)
                      .one(TextureComponent.class, ParticleComponent.class)
                      .exclude(InvisibleComponent.class)
                      .get();
```

Instead only the method `getFor()` is available. Is that the case or am I missing something? If you wish I can update the wiki to reflect the current API

**Comment by KyuBlade** [comment]
Look at the master branch : https://github.com/libgdx/ashley/blob/master/ashley/src/com/badlogic/ashley/core/Family.java

The version you are using seems outdated.

**Comment by luiz-pv9** [comment]
Oh, that's true. Sorry about that.
