### ISSUE TITLE
Possible bug when adding an entity mid update

### ISSUE THREAD

**Issue by 54k** [libgdx/ashley#145]
com.badlogic.ashley.core.Engine#addEntity skips check for update, ~~so ConcurrentModificationException couble be thrown~~.

**Comment by siondream** [comment]
Heey thanks for the ticket. However, I think adding entities mid update is fine, they are added to the end of the entities array and that's it. It doesn't affect iteration like entity removal.

**Comment by 54k** [comment]
Ahh forgot that ashley uses gdx custom collections :)
Anyway I feel that entity additions should be deffered, while engine performs updates.
``` java
// long time ago in a far far system one jedi loops through all entities
for (Entity entity : entities) {
     engine.addEntity(new Entity); // Oops
     engine.removeEntity(entity);
}
```

**Comment by siondream** [comment]
I guess we could defer it for consistency reasons.

**Comment by 54k** [comment]
Yeah, sure.
