### ISSUE TITLE
IteratingSystem does not handle entities added to the engine after the system

### ISSUE THREAD

**Issue by Daiwen** [libgdx/ashley#155]
Hi,
first I would like to tell you I am very happy with what you did with libgdx and ashley !

I was wondering if there were specific reasons why the IteratingSystem was implemented so that it would not handle entities added after the system was itself added to the engine?

Would like me to submit a pull request fixing that? Alternatively would you be interested in me submitting a new EntitySystem abstract class that would do just that? To be clear I am talking of a commented version of the code available there:
https://github.com/Daiwen/TestRoom/blob/master/core/src/com/testroom/systems/DynamicallyIteratingSystem.java

**Comment by siondream** [comment]
`IteratingSystem` holds a reference to the array of entities for its family. The engine will actually update such array as necessary, regardless of the order of operations (adding the system to the engine and adding/removing entities).

That's how references work.

Your `DinamicallyIteratingSystem` has the exact same behaviour as `IteratingSystem`, the only difference is that you update the array reference every `update`, but the reference you will be getting is still the same.

No need for that class.
