### ISSUE TITLE
How to use Ashley the most efficient way?

### ISSUE THREAD

**Issue by wyozi** [libgdx/ashley#165]
I don't mean to come off as rude, but during the development of a fairly simple game I have bumped into some pretty annoying interactions specifically with Ashley, and I'm not sure if I'm just doing the component oriented game development the wrong way or if these were caused by knowingly made choices in developing Ashley.

1. Family that checks for superclass. In my game I wanted to have LightComponent that has PointLightComponent, DirLightComponent etc as subclasses. Because of lack of superclass check in Family I ended up with having a Light object in a single LightComponent class, which is then subclasses further.
2. Access to engine from an entity system. If I want to add a new entity or remove old entity in an entity system, I need to store an engine reference to a field in addedToEngine(), which I think is very annoying as that seems to be a very common thing to do in entity systems.
3. Easy access to up-to-date entities array for specific Family. In my game I wanted to implement parenting entities to other entities, so I created ParentComponent and ParentSystem that extended IteratingSystem. However, adding a ParentComponent to an arbitrary entity did not update the iterated entities in ParentSystem. Instead I had to create an UpdatingIteratingSystem, which keeps the entities array that holds entities with ParentComponents up to date with added entities. Definitely a viable alternative, but even the wiki uses code that keeps an ImmutableArray that is not updated after the system is added to the engine. I feel like that should not be the default option.

I understand some of these choices (namely 1) were made to be performant on mobile phones,  but I feel like they also gimp users. Now the question is are these things that might change in Ashley or should I create my own fork if I want to see them.

**Comment by Antag99** [comment]
> Family that checks for superclass. In my game I wanted to have LightComponent that has PointLightComponent, DirLightComponent etc as subclasses. Because of lack of superclass check in Family I ended up with having a Light object in a single LightComponent class, which is then subclasses further.

That sounds more like object-oriented programming, but making `Light` an abstract base class might be the right thing to do. Components should really only store data, which means there is no need to subclass them (or rather, it's *bad* to subclass them). As a matter of style, always declare them `final`.

> Access to engine from an entity system. If I want to add a new entity or remove old entity in an entity system, I need to store an engine reference to a field in addedToEngine(), which I think is very annoying as that seems to be a very common thing to do in entity systems.

This is what you'll have to do when implementing an own `EntitySystem`. You could declare a common baseclass, say `AbstractEntitySystem`, but I don't think that would look nicer.

> Easy access to up-to-date entities array for specific Family. In my game I wanted to implement parenting entities to other entities, so I created ParentComponent and ParentSystem that extended IteratingSystem. However, adding a ParentComponent to an arbitrary entity did not update the iterated entities in ParentSystem. Instead I had to create an UpdatingIteratingSystem, which keeps the entities array that holds entities with ParentComponents up to date with added entities.

Are you really sure about that?

Adding the `ParentComponent` to an entity will at least show up in the next iteration - such operations may be delayed. I don't understand why `UpdatingIteratingSystem` would be different from `IteratingSystem` - all `ImmutableArray` instances are updated with the entities added to `Engine`.

**Comment by wyozi** [comment]
>Components should really only store data, which means there is no need to subclass them (or rather, it's bad to subclass them).
Subclasses can still hold only data though, can't they? I have no formal education in OOP so I can't say for sure, but if ```Light``` class has a ```attenuation``` field and subclassing ```PointLight``` has a ```position``` field, I don't see how that breaks the store-only-data concept. This was one of my more minor concerns though.

>This is what you'll have to do when implementing an own EntitySystem. You could declare a common baseclass, say AbstractEntitySystem, but I don't think that would look nicer.
Would it be a sensible addition to add eg. ```getEngine()``` to ```EntitySystem```, where default ```addedToEngine()``` would store the engine reference? To me this seems like a very useful addition with no major downsides.

>Are you really sure about that?
No.. I believe I did try it, but didn't do any too comprehensive tests because  I thought ImmutableArray would mean that it is, well, immutable. 

Thanks for the response. I'll see if I can at least get rid of ```UpdatingIteratingSystem```.

**Comment by Antag99** [comment]
> Subclasses can still hold only data though, can't they? I have no formal education in OOP so I can't say for sure, but if Light class has a attenuation field and subclassing PointLight has a position field, I don't see how that breaks the store-only-data concept. This was one of my more minor concerns though.

Yes, fields are inherited from superclasses, so it would work, but wouldn't really suit an ECS design. Rather you could try splitting up `LightComponent` into different components storing some of a lights aspect, and then introduce a `DirLightSystem` handling directional lights, `PointLightSystem` handling point lights, and so on. But I don't really know the right way to go on this one, figure it out yourself.

> Would it be a sensible addition to add eg. getEngine() to EntitySystem, where default addedToEngine() would store the engine reference? To me this seems like a very useful addition with no major downsides.

You could do that in an `AbstractEntitySystem`, or store the engine in a `protected` field, so it's accessible from subclasses. I don't actually think this is too much of a problem, but that is just my opinion.

> No.. I believe I did try it, but didn't do any too comprehensive tests because I thought ImmutableArray would mean that it is, well, immutable.

`ImmutableArray` is just an immutable *view* of an array - the wrapped array can still be modified, which is done by `Engine` when an entity is added/removed to a `Family`. This is indeed very confusing - the only way to find out the truth is by peeking at the `Engine` source code.

**Comment by wyozi** [comment]
I kind of meant would it be possible to add getter for the ```engine``` reference in ```EntitySystem``` in the Ashley code itself.

I know that it then requires subsystems to then call ```super.addedToEngine()``` for it to work properly, but to me that seems like a good trade-off considering many more complex entity systems require access to engine, and while your suggestion of creating ```AbstractEntitySystem``` works well for my own entity systems, it still makes it impossible to get access to ```engine``` in subclasses of built-in entity systems such as ```IteratingSystem``` without overriding ```addedToEngine()```, which is what I want to avoid. 

If that is not a possibility, feel free to close the issue.

**Comment by Antag99** [comment]
You'll have to ask @saltares about that. It's always possible, but I thought it wouldn't really be necessary.

**Comment by saltares** [comment]
##### Lights

Like @Antag99 said, components are just bags of data and should never use inheritance. That's exactly what we're trying to avoid with entity systems in the first place.

Depending on what you want to do I would have different components: `PointLightComponent`, `DirectionalLightComponent` and so on and so forth. You could have a system that deals with entities that possess any light component (this is possible with family filtering) or a system per light type. Whatever suits you best.

##### Entity hierarchy

You could have a `NodeComponent` that would have references to parent and children so you can represent a general tree. A `HierarchySystem` would process these entities if need be. Adding a `NodeComponent` to an entity won't put it in the `HierarchySystem` until the next tick but once that's done, it'll be processed as well. If you have found issues with this or are experiencing a behaviour you might think of as wrong, please create unit test for it and send a PR.

#####Engine access

I will definitely consider making it easier to get an `Engine` reference from an `EntitySystem`. We could even make it so that there is no need to call `super.addedToEngine()` from the derived class. `Engine` could call a final method on the base system that would set the reference to the engine and then call the overridable `addedToEngine()`.

Sorry I haven't been able to stay on top of everything but with work and other compromises it can be rather difficult at times.

**Comment by saltares** [comment]
I think we can close this now, I've created an enhancement ticket for the engine reference from systems.

**Comment by saltares** [comment]
@wyozi #167 is already closed, `getEngine()` is in.
