### ISSUE TITLE
Multiply instances of the same component type

### ISSUE THREAD

**Issue by ArtCraft** [libgdx/ashley#166]
I wonder what is the main reason not to allow entity to contain multiply instances of the same component type?

Here is few use cases:
1. entity represents a box2d body with few shapes or joints attached to it
2. entity represents a character who have few animations
3. entity represents a particle effect with few emitters

Please explain the reason why it is not allowed.
And if you think that allowing it is a bad idea, please suggest some solution that allow to implement this in another way.

**Comment by Antag99** [comment]
> I wonder what is the main reason not to allow entity to contain multiply instances of the same component type?

This should be implemented in your components, or the objects they store.

> 1\. entity represents a box2d body with few shapes or joints attached to it

What's the problem? You could have a `BodyComponent` that simply stores a box2d `Body`.

> 2\. entity represents a character who have few animations

[Here is an example](https://github.com/saltares/ashley-superjumper/blob/master/core/src/com/siondream/superjumper/components/AnimationComponent.java).



> 3\. entity represents a particle effect with few emitters

This is implemented by libgdx's `ParticleEffect`.

**Comment by ArtCraft** [comment]
ok let's focus on example with body that has few shapes
> What's the problem? You could have a BodyComponent that simply stores a box2d Body.

as far as i understand ECS concept, components should contain simple values (easily serializable)
and box2d Body has to be something hidden deep inside PhysicsSystem

I like how it is organized in unity:
![Image](http://i59.tinypic.com/2cfw9it.png)
This is a car
You can see here that this entity has one Rigidbody component and 3 shape components (Box Collider 2D and 2x Circle Collider 2D) 
Nice and clean isn't it?

**Comment by Antag99** [comment]
> as far as i understand ECS (Entity-Component-System) concept, components should contain simple values (easily serializable)
> and box2d Body has to be something hidden deep inside PhysicsSystem

No, that is not necessary, as long as components do not implement game logic. Anyone who wants to access the `Body` of an entity just retrieves the `BodyComponent`. I do not see why splitting up a `Body` into different components would be better, as everything is already implemented by Box2d. You ain't gonna need to process entities with circle shapes separately, right?

**Comment by ArtCraft** [comment]
But i'm gonna need serialize all compnents for each entity ( to save level for example )
Also, potentially, if my components don't contain any framework dependencies it will give me possibility to use it with any physics engine, only by rewriting PhysicsSystem

so having any complex data stucture, or 3d party framework object inside comonents parameter looks like really bad idea for me

**Comment by saltares** [comment]
@Antag99 thanks for helping out with issues :-).

> But i'm gonna need to serialize all compnents for each entity ( to save level for example )
Libgdx provides a [JSON serialization API](https://github.com/libgdx/libgdx/wiki/Saved-game-serialization). You can always add serialization capabilities to more complex components and add your game save logic in there. The serialization logic can be done either in the `BodyComponent` or in a separate `BodySerializer` class.

**Comment by saltares** [comment]
I'm going to close the issue. Feel free to re-open if you have other questions.
