### ISSUE TITLE
Make it easier to get an Engine reference from an EntitySystem

### ISSUE THREAD

**Issue by saltares** [libgdx/ashley#167]
See issue #165 for details.

**Comment by saltares** [comment]
@Antag99 what do you think would be the best thing to do here?

We need:
* Getter for `Engine` inside `EntitySystem`.
* It'd be nice for user derived `EntitySystem` subclasses not to have to call `super.addedToEngine()` every time.
* Robust and as least error prone as possible.

I suggest:
* Add a `final` package protected method to `EntitySystem` that `Engine` will use to set the reference.
* This method will call `addedToEngine()` which has a default empty implementation and it's designed to be overridden. No API changes here.

Name suggestions for the new methods?

* `registerWithEngine()` and `unregisterFromEngine()`?
* `registerWithEngineInternal()` and `unregisterFromEngineInternal()`?

**Comment by Antag99** [comment]
> Name suggestions for the new methods?

Maybe `addedToEngineInternal()` and `removedFromEngineInternal()`? Just an idea.

Demanding to call `addedToEngine()` inside subclasses is indeed error-prone, which is required if you extend `IteratingSystem` or any of the other build-in entity systems.

**Comment by saltares** [comment]
Thanks for the input.
