### ISSUE TITLE
Wiki - Components example

### ISSUE THREAD

**Issue by JamesSkemp** [libgdx/ashley#176]
In the [How to use Ashley wiki page](https://github.com/libgdx/ashley/wiki/How-to-use-Ashley#components) there's the following:

> So, if you try to add two instances of the same class, the second one will replace the old one.

>     entity.add(new PositionComponent());
>     entity.add(new VelocityComponent());

As a first time reader this is a confusing example, as these are different classes. Perhaps an example with two `PositionComponent` objects being added would be better?

**Comment by Antag99** [comment]
The intention of the code snippet is to show how to add components to an entity, not that two components of the same type will override each other. I think this should be fixed by moving the warning to after the code snippet.

**Comment by JamesSkemp** [comment]
An even better idea.

I've submitted an edit to the wiki page that does this.

**Comment by saltares** [comment]
Thanks!
