### ISSUE TITLE
A C++ port of Ashley

### ISSUE THREAD

**Issue by Lusito** [libgdx/ashley#177]
Not exactly an issue, but I've ported Ashley to C++, since there are no good ECS for C++ out there:
https://github.com/Lusito/ECS-tasy/tree/develop
It's still in beta, and [a couple of things](https://github.com/Lusito/ECS-tasy/wiki/Differences-to-Ashley) have been rewritten to take advantage of C++11.
All Unittests have been ported as well and are passing.

Let me know if there's anything that should be different.

**Comment by Antag99** [comment]
> Not exactly an issue, but I've ported Ashley to C++, since there are no good ECS for C++ out there:
> https://github.com/Lusito/ECS-tasy/tree/develop

Why C++? :p

> Let me know if there's anything that should be different.

AFAIK, only one pool implementation is necessary, due to C++'s compile-time template system.

**Comment by saltares** [comment]
So far I love the logo and the subtitle.

> Ashley on ~~Speed~~ C++.

I'm quite low on time these days so will try to check it out as soon as I can. I think it's a brilliant idea though! :-).

**Comment by junkdog** [comment]
> there are no good ECS for C++ out there

[entityx](https://github.com/alecthomas/entityx) is probably the most popular one; there are several others ones around, but many appear to be direct and sloppy ports from old artemis (and are now left to rot). entityx is pretty good though (one of few C++ ECS:s employing [CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern)/static polymorphism for `EntitySystem::process(Entity)`, which I thought was a pretty neat trick).

I had a quick look at the code: a few things that stood out:
- Systems subscribe to pointers-to-Entities: I'd personally prefer having something more streamlined. I've been using:

```c++
namespace ecs {

struct Entity {
	friend class ComponentManager;
	friend class EntityManager;
	friend class System;

  public:
	Entity(u_int32_t id) : id(id) {}
	~Entity() = default;
	u_int32_t getId() const;
	bool operator==(const Entity& rhs) const;

  private:
	u_int32_t id;
};
```

The above entity is just 4 bytes in size, so it's generally cheaper to copy the entity vs storing a pointer to it, and it gives better cache locality when iterating.

- I'd decouple the components from the entities: better to have a `ComponentStore<T>` or component manager in the long run. Imo, bundling more data than a mere `id` in Entity was one of the biggest design mistakes in artemis - and now pretty much all other ECS frameworks have copied it. This is less of problem if you don't care about performance.
- A lot of pointers passed around everywhere (or maybe it's just the code I happened to look at). I'd rather have references or copies; I don't want to check for nullptr if I don't have to.
- It looks like you're storing a vector of pointers-to-components per entity? Consider pre-allocating a `vector<Component>` per type (`std::vector<Positon>`, `std::vector<Velocity>` etc). This yields better perf overall. Furthermore, it makes pooling a moot point, as all memory (aside from growing the vectors) is done at start-up.
- Bits doesn't overload the subscript operator; check out how [std::bitset](http://www.cplusplus.com/reference/bitset/bitset/operator%5B%5D/) does it - you basically need to use a proxy to read/write individual bits). It's a convenience more than anything else, but very nice to have.
- Where's my CMake? ;) (ok, it's early in dev, but consider adding one - makes it easier to integrate in projects).
- I know this isn't how ashley works. but recycling entity id:s makes life easier - and it is an implied consequence by some of my suggestions above.

**Comment by Lusito** [comment]
>Why C++? :p

Because C++ is the top language for games?

>AFAIK, only one pool implementation is necessary, due to C++'s compile-time template system.

Could you explain further please, I'm not sure what you mean.

>entityx is probably the most popular one;

Yes, I'm actually working with it on a team-project at my university, but it lacks seriously in documentation and even tho it uses a powerful 3rdparty signal system, it hides most of its features.

>Systems subscribe to pointers-to-Entities: I'd personally prefer having something more streamlined. I've been using:...
>I'd decouple the components from the entities:...

I'm unsure as to how that would work. But even if, wouldn't it be better to use a typedef uint32_t instead of creating a class that does nothing more than containing an int ?

>A lot of pointers passed around everywhere 

I guess this is mostly due to the !(above), but I'll take a look at it.

>It looks like you're storing a vector of pointers-to-components per entity?

Same reason as above. Also.. how would you do that in a generic way without knowing the components ?

>Bits doesn't overload the subscript operator

Yes, it's on my todo list

>Where's my CMake? ;)

Haven't used it yet. I'll take a look at it.

>I know this isn't how ashley works. but recycling entity id:s makes life easier.

How would you make sure that an old entity id is still valid, if the entity has been destroyed and a new one has been created with the same id ?

**Comment by SgtCoDFish** [comment]
Haha I did the same thing quite a while ago to learn the new C++11 stuff! :) [AshleyCPP](https://github.com/SgtCoDFish/AshleyCPP)!

I'll have to take a look at your code and see where we match/differ :)

**Comment by Antag99** [comment]
> Could you explain further please, I'm not sure what you mean.

Well, I think it would be possible to reduce the number of pool classes by using a single template class. ReflectionPool could be made the only pool implementation; perhaps with the possibility to override the default `newObject()` method, in case something special would be required. I guess ReflectionPool is a separate class in libgdx as there is no runtime types for generics in Java, which makes it impossible to instantiate objects using the no-arg constructor of them by default.

**Comment by junkdog** [comment]
> I'm unsure as to how that would work. But even if, wouldn't it be better to use a typedef uint32_t instead of creating a class that does nothing more than containing an int ?

A typedef is only an alias. The entity struct is just there to wrap it in a type; this doesn't add any overhead at runtime, ie; `sizeof(uint32_t) == sizeof(ecs::Entity)`.


> Same reason as above. Also.. how would you do that in a generic way without knowing the components ?

I have s [Store](https://github.com/junkdog/arethusa-ecs/blob/master/src/Store.h) template class for each component type. In turn, the component manager has a vector with pointers-to-component stores:

```c++
std::vector<std::unique_ptr<BaseStore>> stores;
```

You need a base, non-template, parent class - as you can't have a vector of `Store<?>*`. When retrieving the store (or component vector, whatever you have), [cast it](https://github.com/junkdog/arethusa-ecs/blob/master/src/ComponentManager.h#L54) to the correct type. The component stores are created on demand.


> How would you make sure that an old entity id is still valid, if the entity has been destroyed and a new one has been created with the same id ?

From which point of view? It's up to the user to make sure that they listen for entity state events and don't hold onto deleted entities. On the framework end, the ids of all deleted entities are added to an array at the start of each processing round (entities are however inserted into/removed from systems prior to processing each system). When creating a new entity, pop an int from the array or return the next id.

btw; take what I say and code with a grain of salt. I'm not really particularly experienced w.r.t. C++, I'm sure the code contains a lot of silliness etc.

**Comment by Lusito** [comment]
>Haha I did the same thing quite a while ago to learn the new C++11 stuff! :)

Nice. On a short look it seems you preserved more of the original code with ComponentMappers & such, but I'll give it a deeper look another time.

>Well, I think it would be possible to reduce the number of pool classes 

Ah, yes that should be possible. I'll try that.

>The entity struct is just there to wrap it in a type

Ah, my mistake, I thought typedef'ed ints would be typesafe.. that means I have some things to change in my code. Thanks for the hint.

>You need a base, non-template, parent class

ok, I get it.. I'll think about it.

>entities are however inserted into/removed from systems prior to processing each system

So you create the list of entities that match a family every time before a system is called ? that sounds like a lot of work that is done possibly multiple times a frame instead of just on changes.

**Comment by Lusito** [comment]
>Bits doesn't overload the subscript operator

Using it instead of get would be possible, but set is a different story, since the operator is executed before the assignment. It can be done by creating a new class which can be returned as a reference, but I'm not sure it's worth it.

**Comment by junkdog** [comment]
> So you create the list of entities that match a family every time before a system is called ?

No, each system has its own list of entities - a single processing round looks something like this: http://i.imgur.com/ARNefV6.png

You're probably better off if you separate the entity subscriptions from the systems, and only refresh the subscriptions as needed (as in, when the system starts processing).

**Comment by Lusito** [comment]
Looks like a major rewrite to me. I don't have the time right now, but I will keep it on my todo list to try it.
It would be interesting to see the difference in memory consumption and performance. If it's not too much difference, I'd probably stay with the current way, as it has the benefit of being more intuitive to use and does not require the user to have a reference to the engine if he wants to do something with an entity.

**Comment by junkdog** [comment]
[Scott Meyers: Cpu Caches and Why You Care](https://www.youtube.com/watch?v=WDIkqP4JbkE) - but it's probably better to have benchmarks in place before refactoring.

**Comment by Lusito** [comment]
Thanks for the link. I finally got around to taking a closer look at it.
Since entityx takes the approach of managing all entities and components inside of the manager, I thought it would be a good test to make a benchmark of entityx vs ecstasy.

The test setup:
- One Engine
- Two Component Types
- 4 Systems that iterate a family, doing some work on the components ( 2 systems per component type).
- 10000 Entities added
- Each entity gets random components (none, a, b or a & b). The seed is always the same, so the benchmark is behaving the same way every time.

The code is here:
- https://github.com/Lusito/ECS-tasy/blob/feature/benchmarks/benchmarks/entityx.cpp
- https://github.com/Lusito/ECS-tasy/blob/feature/benchmarks/benchmarks/ecstasy.cpp

The results on Visual C++ 2013:

    ECStasy                                     100    13470771 ns/op
    entityx                                      20    53203045 ns/op

On TDM GCC 4.8:

    ECStasy                                      50    31361800 ns/op
    entityx                                      20    73454200 ns/op

The time is an average nanoseconds per call to engine.update()
This makes entityx ~4 times slower on msvc and ~2.3 times slower on gcc

My guess is, that the benefits of the cpu cache is outweighed by branch prediction issues.
Or maybe the checks for matching component masks during iteration cost too much time.

Thoughts ?

Aside from this benchmark, I did port an existing Game that was written with entityx to ecstasy and it performed slightly faster (~5%). Interestingly, the binary was slightly smaller and the consumed memory as well. I expected it to take more ram than entityx.

**Comment by antag99** [comment]
> Thoughts ?

Go for smaller components (1-8 floats each), more component types and more entities. Go for at least 2^15 entities, 8 component types and 8 system types... The goal is to accurately benchmark normal usage; 1kb-sized components might not be a good idea.

**Comment by Lusito** [comment]
I adapted the tests to your specifications, but there is little change in the results.

**Comment by antag99** [comment]
I rewrote the benchmarks and got these results, see Lusito/ECS-tasy#2.

```
ECS-Tasy                                    100    11235927 ns/op
entityx                                     500     2915293 ns/op
```

**Comment by Lusito** [comment]
I don't really see how the new code is more accurate..
You completely removed the randomness, allowing the cpu to predict branches. Something you can't control in a normal game.
And for some reason you call the systems on the entityx benchmark manually, which is kind of besides the point of an ecs.

Just changing these 2 back makes the difference less impressive:

    entityx                                     500     4430252 ns/op
    ECS-Tasy                                    200     6880390 ns/op

Apart from that, the only changes I see are:
- More entities
- Less systems
- Less component types
- Less component data
- No loops in the systems

The last one should not make any difference, since it's the same for both.
After trying some of these changes on my original code, I'd say the changes that are responsible for the different result boil down to more entities.

I wouldn't say 131072 entities is normal usage. It did make me curious however.
Going even further with the number of entities shows a great disadvantage of ecstasy for higher entity counts. I will try to find out why exactly that is.

**Comment by antag99** [comment]
> You completely removed the randomness, allowing the cpu to predict branches. Something you can't control in a normal game.

I reintroduced the randomness; I don't think this matters too much, as the conditions should change pretty often anyway, but I've not read into it.

> And for some reason you call the systems on the entityx benchmark manually, which is kind of besides the point of an ecs.

Fixed that too; but it seems like the performance *improved*; probably completely unrelated. ;)

>* Less systems
>* Less component types
>* Less component data

I was too lazy to copy paste some more... templates might affect the results, as well as using arrays.





> No loops in the systems

Nope; doesn't have anything to do with the ECS. I added `++` operations to trick the compiler into not doing optimizations such as removing the entire thing.

> I wouldn't say 131072 entities is normal usage. It did make me curious however.
> Going even further with the number of entities shows a great disadvantage of ecstasy for higher entity counts. I will try to find out why exactly that is.

No; it's meant to more accurately benchmark it. Changed it back, didn't yield different results.

> Just changing these 2 back makes the difference less impressive:
> 
> entityx                                     500     4430252 ns/op
> ECS-Tasy                                    200     6880390 ns/op

Here's what I got on my fork after the changes you mentioned:

```
ECS-Tasy                                    500     4620022 ns/op
entityx                                    1000     1947092 ns/op
```

You might want to run them yourself; but make sure to pass `config=release` to make.


I'm not really sure about the benchmark harness; there might be a better alternative out there.

**Comment by Lusito** [comment]
>I reintroduced the randomness; I don't think this matters too much, as the conditions should change pretty often anyway, but I've not read into it.

http://stackoverflow.com/questions/11227809/why-is-processing-a-sorted-array-faster-than-an-unsorted-array

>Fixed that too; but it seems like the performance improved; probably completely unrelated. ;)

I noticed a small inprovement as well. probably optimizations. Nothing that would skew the results tho.

>templates might affect the results

Why is that ?

>No; it's meant to more accurately benchmark it.

The testing framework dynamically adds more runs to it if necessary. That is why you see different number of iterations when changing code (the left number in the output)

>You might want to run them yourself; but make sure to pass config=release to make.

I always run benchmarks in release mode.. running them in debug would be pointless.

>I'm not really sure about the benchmark harness; there might be a better alternative out there.

If you find something, let me know.. This was the best I found on a 20 minute google search. Had to rewrite it a bit to exclude construction and destruction time from the results tho.

I'm guessing we get different results due to differences in ram and/or cpu cache sizes. Or maybe you are on linux ? gcc results differ quite a bit on windows.

**Comment by Lusito** [comment]
> Here's what I got on my fork after the changes you mentioned:

Either you didn't commit those changes correctly, or you mistyped: I had 2 << 14 in my tests, not 2 << 15.

your code latest code (2 << 15 entities):

    entityx                                     200     5515315 ns/op
    ECS-Tasy                                    200     7460430 ns/op

same code with 2 << 14 entities:

    entityx                                     500     2058118 ns/op
    ECS-Tasy                                   1000     1103063 ns/op

**Comment by antag99** [comment]
> > I reintroduced the randomness; I don't think this matters too much, as the conditions should change pretty often anyway, but I've not read into it.
> 
> http://stackoverflow.com/questions/11227809/why-is-processing-a-sorted-array-faster-than-an-unsorted-array

What I meant is that the CPU can't perfectly predict branches as in the StackOverflow question; the entity compositions vary quite much.

> > templates might affect the results
> 
> Why is that ?

Code generated by templates might lead to worse compiler optimizations; just guessing here.


> I'm guessing we get different results due to differences in ram and/or cpu cache sizes. Or maybe you are on linux ? gcc results differ quite a bit on windows.

I'm on LInux. Are you running the benchmarks from Visual Studio? I believe you're doing something really wrong, to be honest.

> your code latest code (1 << 15 entities):
> ```
> entityx                                     200     5515315 ns/op
> ECS-Tasy                                    200     7460430 ns/op
> ```

My results:
```
ECS-Tasy                                    200     5358471 ns/op
entityx                                     500     2043539 ns/op
```

> same code with 1 << 14 entities:
> ```
> entityx                                     500     2058118 ns/op
> ECS-Tasy                                   1000     1103063 ns/op
> ```

My results:
```
ECS-Tasy                                   1000     1977498 ns/op
entityx                                    1000     1011370 ns/op
```

**Comment by saltares** [comment]
FYI: https://github.com/google/corgi

I personally don't like its design, components also act as systems. What do you guys think?

**Comment by Lusito** [comment]
I don't think it's very usable.. logic bound to components means you can't do logic that matters to a family without putting it into any of the components logic, where it could possibly make code ugly depending on how many cases like this there are.

**Comment by saltares** [comment]
I think we can close this now.
