### ISSUE TITLE
Moving entities between engines

### ISSUE THREAD

**Issue by lukz** [libgdx/ashley#180]
I'm using Ashley in [Angry John](http://angryjohngame.com) and I reached moment in development when I want to move Player and all it's equipment between levels.

In every level I create new Ashley Engine. I was thinking about keeping Player Entity and adding it (and all Entities in Equipment) to new Engine but it's impossible because Entity has non zero UUID and exception is thrown. As far as I know it's impossible to reset UUID. Also it would be necessary to recreate Entities Box2D bodies but that should be easy.

Is there any suggested way to tackle that problem?

**Comment by lukz** [comment]
Ok, I didn't noticed that Engine.removeEntity resets UUID but if anyone have some suggestions in player progression subject I would love to hear them.

**Comment by antag99** [comment]
In my opinion, Ashley should drop support for UUIDs - such things should be implemented by users. This may imply removing the checks for adding an entity twice, but that shouldn't matter too much - it can always be reimplemented later.

I think moving an entity between engines is wrong. Maybe you could use the same engine for different levels?

**Comment by lukz** [comment]
@antag99 I think that cleaning up Engine can introduce more bugs that recreating from scratch and moving entities. Also later I can serialize / deserialize entity and make it consistent with save / load. I managed to get it working the way I described and so far looks good ;)
