### ISSUE TITLE
Make it easier to extend ashleys classes

### ISSUE THREAD

**Issue by GameplayJDK** [libgdx/ashley#183]
Currently the classes mostly have `private` variables, which makes it difficult to extend them ,because some of them can not be accessed using `this` or `super` and also don't have a getter.

This is essential for the game I'm currently developing. I separated the game logic and the render logic, which means that I have a `render()` and an `update()` method that are required in my entitysystems. It wouldn't be difficult to have a plain method or interface to do that, but I can not use my version of the engine class to call it. To do so I would need access to the [`updating` boolean](https://github.com/libgdx/ashley/blob/master/ashley/src/com/badlogic/ashley/core/Engine.java#L72-L74) (at least in theory)...

Changing the access modifier from `private` to `protected` would solve all my issues.

**Comment by antag99** [comment]
Exposing this kind of information makes breaking changes unavoidable as the project moves forward - Ashley is already pretty bad in this sense.

You should use different systems for updating and rendering - then it's simply a matter of running rendering system after all logic systems have been executed.

**Comment by saltares** [comment]
I think @antag99 pretty much gave you the solution to your problem. The state you want us to expose is meant to be abstracted away, this would cause more problems than it would solve.

**Comment by GameplayJDK** [comment]
I though about using a system for that, but, as I mentioned, I have those two methods. `update()` runs 60 times per second while `render()` is not bound to a fixed rate. I decided to use that design to separate my game logic from the rendering (and to have a fixed timestep for box2d).

Thank you for making me think about that :) My plan is now to just keep a reference to my render system and and execute it's custom `render()` when needed.

**Comment by saltares** [comment]
You can use [`IntervalSystem`](https://github.com/libgdx/ashley/blob/master/ashley/src/com/badlogic/ashley/systems/IntervalSystem.java) for that.

**Comment by GameplayJDK** [comment]
@saltares That's event better! Thanks

**Comment by saltares** [comment]
Closing this for now then :-).
