### ISSUE TITLE
Entity listeners are not called when adding a component inside a listener

### ISSUE THREAD

**Issue by chartinger** [libgdx/ashley#184]
Scenario:

Given i want to decouple logic and render components/systems, i may end up with something like this:

A "Star Render System" listens if an entity with a "StarComponent" was added to the engine. If so, it adds a "DrawableComponent" with the render details to this entity.
The expectation would be that the component is added and the listeners on entities with "DrawableComponent" are called (and therefore all getEntitiesFor arrays will be updated).

Currently, the component is added as expected (e.g. can be accessed via entity.getComponent) but no listeners are called.

**Comment by saltares** [comment]
I think this is similar to #161.

However, you may want to have some sort of `EntityFactory` that can add entities with all its components, such as "star". You won't need to add components via listeners that way.

That is a potential workaround, will try to get around to fix this issue as soon as I can. It will probably require making some slight API changes.
