### ISSUE TITLE
Updating family membership allocates memory

### ISSUE THREAD

**Issue by saltares** [libgdx/ashley#189]
See https://github.com/libgdx/ashley/blob/master/ashley/src/com/badlogic/ashley/core/Engine.java#L325

**Comment by junkdog** [comment]
Didn't you forget to free the Bits instances? (alternatively, I'm missing something obv, long nights and all)

**Comment by saltares** [comment]
And I've been on a trip this weekend, sleep deprived. Fail.

**Comment by saltares** [comment]
Fixed https://github.com/libgdx/ashley/commit/b8a37eb35dfd4fc1e38268d84a3ee1f46eb5236f

Thanks a lot for the code review!
