### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by mars3142** [libgdx/ashley#192]
It would be nice, if someone who tags a new version, would also update the https://github.com/libgdx/ashley/releases page with a small change log or something similar. That would be helping to decide, if someone needs the update or not.

PS: I don't want to read the whole commit-history to see what's new/changed.

**Comment by saltares** [comment]
Right now, that happens on [the blog](http://saltares.com/blog/) but you're right. We should add these to the changelog of every release as well.

Let's use this ticket to update them retroactively and add a `Changelog.md` file to the repo to keep track as we go.

**Comment by saltares** [comment]
See https://github.com/libgdx/ashley/releases
