### ISSUE TITLE
Is it possible to add a Component instance to multiple Entities?

### ISSUE THREAD

**Issue by ttencate** [libgdx/ashley#195]
For example, I have a character consisting of multiple body parts, which are separate entities. But they should all live and die as one, so I would like to add the same `HealthComponent` to all of them. Or I might have a "marker" or "tag" component, which doesn't contain any fields, so I could just reuse the same instance over and over.

Is this supported?

How about with pooled components (I imagine not)? But even if a component is normally pooled, can I create a `new` one outside the pool for such a purpose?

Either way, I will make sure to document the answers on the wiki :)

**Comment by saltares** [comment]
Wouldn't it be easier to have a `MultiBodyPhysicsComponent`? That way you wouldn't need to share components across entities.

An even simpler alternative would be to use multiple fixtures to represent the body parts and only use a regular `PhysicsComponent` with a single body.

**Comment by ttencate** [comment]
Thanks for the reply! Is that the usual way of tackling such a problem in an ECS, having multi-body (and thus multi-position, multi-sprite, multi-everything) components? It seems to go contrary to the spirit of an ECS, but what do I know.

The different body parts have different behaviours, so I need to keep track of which is which, and make my other Components act on the right body. They also each have a sprite, so I'd need to map bodies to sprites (though this could currently be a 1:1 correspondence by array index).

Pooling also becomes more difficult when a component contains an array: do you shrink the array in the `reset()` method, possibly causing garbage collection, or do you keep it at the largest size it ever needed to be, possibly causing memory leaks?

As to your simpler alternative: multiple fixtures are all part of the same rigid body, so they cannot move relative to each other, nor be connected with joints. And anyway, the issue is more general, not just related to Box2D bodies.

**Comment by arapidhs** [comment]
I believe the parts should be kept as different entities. Especially since they have their own behaviour.
What you can do is to introduce a new GroupComponent that stores the entity ids of the body parts, and a ParentComponent that optionally would store the id of the parent - it depends on your needs.

In the end, you'd have a new entity that has two components; GroupComponent and HealthComponent.
All your body parts would have a ParentComponent. Whenever a body part is damaged and has a ParentGroup component, fetch the parent entity by its id and get its HealthComponent.

**Comment by ttencate** [comment]
Thanks. That's roughly what I'm doing at the moment, but it's a hassle to follow the pebble trail and check for nulls all the time (HealthComponent isn't the only place where I need to share this state).

An alternative I considered was to have separate HealthComponent instances, but each contains a reference to the same HealthModel object where the health is tracked. But additional objects, additional indirections, more GC... which is why I wondered whether I could get away with just reusing the component itself.

About which I'm still not sure, actually. Can I? Or will this break Ashley in horrible ways?

**Comment by saltares** [comment]
> I wondered whether I could get away with just reusing the component itself.

Definitely not if you're using `PooledEngine` and your components implement `Poolable`, otherwise those will be disposed and reset whenever a body part is freed, screwing with your setup.

I think @arapidhs 's idea is not a bad one.

**Comment by ttencate** [comment]
OK, thanks for your insights!
