### ISSUE TITLE
More control over ComponentType

### ISSUE THREAD

**Issue by dveyarangi** [libgdx/ashley#198]
Hey,

I just noted I cannot get components using mapper for component interface, for example for this hierarchy:
```
interface IRenderingComponent
class SpriteRenderingComponent implements IRenderingComponent
class AnimationRenderingComponent implements IRenderingComponent
```
I'd expect to be able to create mapper using IRenderingComponentinterface, but this does not work.
This due to the fact that new ComponentTypes are being generated per class name.

It seems soluble by either
1) Allowing to extend the ComponentMapper or other way specify the ComponentType it uses.

2) Switching ComponentType to singleton instead of static and allow setting the singleton by custom overriding class, that will provide ComponentTypes as wanted.

3) More integrated solution would look something like:
```
class ComponentType {
...
	public static ComponentType registerFor(Class<? extends Component> baseType, Class<? extends Component> childType) {
		ComponentType type = getFor(baseType);
		assignedComponentTypes.put(childType, type);
		return type;
	}
...
```
and then
```

ComponentType.registerFor(IRenderingComponent.class, SpriteRenderingComponent .class);
ComponentType.registerFor(IRenderingComponent.class, AnimationRenderingComponent .class);

ComponentMapper<IRenderingComponent> mapper = ComponentMapper.getFor(IRenderingComponent.class);
```
by simply mapping the same several classes to same ComponentType

I could make the change in Ashley by myself, if this seems reasonable.

**Comment by dveyarangi** [comment]
To justify my approach, in this specific example, I created a rendering entity system, that groups the entities by context, which is currently either texture instance or shape renderer. The system uses IRenderingComponent#getContextId() to determine the rendering context.

The system then invokes the IRenderingComponent#render() method in batches during update.

**Comment by saltares** [comment]
I have faced a similar issue in the libGDXJAM. Our renderer has to render entities with different family configurations.

You can use

**Comment by saltares** [comment]
I really don't want to change the Ashley API and I think this issue can be overcome as explained [here](https://github.com/libgdx/ashley/issues/207#issuecomment-171780053).
