### ISSUE TITLE
Family#Builder methods

### ISSUE THREAD

**Issue by dveyarangi** [libgdx/ashley#200]
Hey,

I just noted that Family builder methods (one, all, exclude) have the same implementation, all implementing "all" functionality.

**Comment by saltares** [comment]
That's just not true. Have you seen the [code](https://github.com/libgdx/ashley/blob/master/ashley/src/com/badlogic/ashley/core/Family.java)? 

Can you provide with a unit test exhibiting the issue? If what you say is true, this [test](https://github.com/libgdx/ashley/blob/master/ashley/tests/com/badlogic/ashley/core/FamilyTests.java#L258) would definitely fail.

Closing issue until more information is provided.
