### ISSUE TITLE
SortedIteratingSystem behaving weird

### ISSUE THREAD

**Issue by Nauktis** [libgdx/ashley#201]
I took back an old project of mine and updated Ashley from version 1.4.0 to version 1.7.0.
Compilation wise, no problems appart from the Component that became an interface (good)
But I'm having problem with SortedIteratingSystems

I created one with the following familly: `Family.all(PositionComponent.class, SpriteComponent.class)`
But in my `Comparator<Entity>`, I'm getting NPE because I receive entities without those components!
I guess this is a bug? Maybe related to the recent changes regarding components being removed immediately?

**Comment by saltares** [comment]
Could you write a test case that highlights the issue? That way we can prove it's broken and enter a fix for it! :-).

**Comment by Nauktis** [comment]
This was actually due to the bug #203 ;)
