### ISSUE TITLE
ECS and SortedIteratingSystem

### ISSUE THREAD

**Issue by Nauktis** [libgdx/ashley#207]
I'm facing an issue in my current design. It is more related to Entity Component System in general than Ashley but since it's using `SortedIteratingSystem`, I still post here.

In my current design I have a `SpriteComponent` which contains a texture.
I then have a `RenderingSystem` which is a `SortedIteratingSystem`.
It sorts the entities based on their layer (Background, Main, Foreground) and on their position and then renders them by simply drawing the texture from their `SpriteComponent`.
Simple enough and it works like a charm.

Now, my problem is that I start to have entities which require custom rendering logic. (Solar panels should have a bar showing the sun level, silos should indicate how full they are, people are composed of two textures with relative positions, animation, etc.)
In pure OO, each of those object would override its `draw()` method and implement his own drawing logic. But in ECS, I don't really now how to go about it.

It is the `RenderingSystem` that sorts the entities before drawing them so somehow, the logic should be captured in there. But I would like to avoid having a big switch statement in the system with all the custom drawing logics together.

My question is therefore, how would you implement such a thing in a pure ECS way?

**Comment by saltares** [comment]
Your `RenderingSystem` would be a `SortedIteratingSystem` with a family that looks like the following:

```
Family.all(
    PositionComponent.class,
    LayerComponent.class,
    SpriteComponent.class,
).one(
    SolarPanelComponent.class,
    PlayerComponent.class
).get();
```

If you have animations, you could have an `AnimationSystem` that processes entities with `AnimationComponent` and `TextureComponent` and each frames sets the right texture region on the texture component according to the animation frame list and time in the animation component.

Does this answer your question?

**Comment by Nauktis** [comment]
Thanks a lot for taking the time to give me some directions :)

You mean something like this then for my `RenderingSystem`:
```
void processEntity(Entity entity, float deltaTime) {
  
  if (entity.getComponent(SolarPanelComponent.class)) {
    // Add custom solar panel rendering
  }
  
  if (entity.getComponent(PlayerComponent.class)) {
    // Add custom player rendering
  }
  
  if (entity.getComponent(FooComponent.class)) {
    // Add custom foo rendering
  }
  
  if (entity.getComponent(BarComponent.class)) {
    // Add custom bar rendering
  }
  
  // ... And so on and so forth
}
```

I miss polymorphism :(

**Comment by saltares** [comment]
`entity.getComponent()` is `O(logn)`, you should be using [mappers](https://github.com/libgdx/ashley/wiki/How-to-use-Ashley#retrieving-components-with-componentmapper).

And yes, you're right, this would benefit greatly from polymorphism, you're not the first one who mentions it #198.

To be honest, I'd rather not break existing API. Ashley is now used by quite a lot of people, so don't want to break their code every time. Will still have a think about it to provide a nice way of doing this.

**Comment by mwohlf** [comment]
I solved this by using "HasRenderables" components, the render logic is hidden in different implementations of a Renderable interface, the implementations are stored in "HasRenderables".
The main Render method fetches the Renderable from the Component and just calls their render method. (I hope this makes sense; you can see some code here: https://github.com/mwohlf/pluto)

**Comment by Nauktis** [comment]
Indeed this is also an idea I had where you can use polymorphism again but what you actually end up doing by this is to somehow move the logic in the component !

Which goes a bit against the idea of the component/system split.

But it might be the best trade off!

**Comment by mwohlf** [comment]
well, the logic is not implemented in the component, the component is just a container for an object that implements the logic, you can see it somehow as  strategy or command pattern (at least that"s what I am telling myself so i don't feel to bad oabout this solution ;-)

**Comment by saltares** [comment]
Maybe not the prettiest solution but it keeps the logic inside the system. I think the code is self-explanatory.

```java
public interface Renderable {
    
}

public class TextureRenderable extends TextureRegion implements Renderable {
    
}

public class RenderableComponent implements Component {
    public Renderable renderable;
}

public class RenderingSystem extends IteratingSystem {
    private ObjectMap<Class<? implements Renderable, Renderer> renderers;

    public RenderingSystem() {
        super(Family.all(RenderableComponent.class).get());

        ...
    }   

    protected void processEntity(Entity entity) {
        ComponentMapper<RenderableComponent> rm = ComponentMapper.getFor(RenderableComponent.class);
        RenderableComponent renderableComponent = rm.get(entity);
        Renderer renderer = renderers.get(renderableComponent.renderable.getClass());
        renderer.render(entity);
    }

    private interface Renderer {
        public void render(Entity entity);
    }

    private class TextureRenderer implements Renderer {
        public void render(Entity entity) {

        }
    }
}
```

The renderers don't need to be inside the `RenderingSystem`, rendering logic can be nicely split.

**Comment by saltares** [comment]
I think the question was answered, closing.
