### ISSUE TITLE
Family.all(Clazz.class).one(Clazz2.class, Clazz3.class).get not possible

### ISSUE THREAD

**Issue by mars3142** [libgdx/ashley#211]
It is not possible to combine **all**, **one** and/or **exclude**. How can I filter all entities with Clazz that has at least Clazz2 or Clazz3? As far as I see in code, every call does a reset. 

The only way is to do it manually in processEntity, right?

**Comment by Courthold** [comment]
Combining `all`, `one` and `exclude` should work fine [as shown here](https://github.com/libgdx/ashley/wiki/How-to-use-Ashley#entity-families). Are you having a specific problem with it not working?

`reset()` is only called for the initial method call on `Family` and then the remaining chained methods are  inside the static `Builder` class which do not reset ([seen here](https://github.com/libgdx/ashley/blob/master/ashley/src/com/badlogic/ashley/core/Family.java#L124)

**Comment by saltares** [comment]
We also have [tests](https://github.com/libgdx/ashley/blob/master/ashley/tests/com/badlogic/ashley/core/FamilyTests.java#L94) demonstrating family filtering. 

If you're experiencing issues, do you mind writing a small unit test that highlights the problem? That way, it'd become a lot easier to tackle the issue.

**Comment by saltares** [comment]
Will withdraw as this doesn't seem to be an issue.
