### ISSUE TITLE
Missing type error in GWT when using PooledEngine (1.7.0)

### ISSUE THREAD

**Issue by meisterfuu** [libgdx/ashley#218]
With Ashley version 1.7.0 I cannot run a gwt build while using a PooledEngine. The not pooled engine works fine.

According to the changelog this was fixed in 1.3.1 with the commit cb33472. But I get the "missing type for class" error with 1.7.0 too.

```
GwtApplication: exception: Couldn't find Type for class 'de.test.libgdx.gwt.components.EarlGrey'
Couldn't find Type for class 'de.test.libgdx.gwt.components.EarlGrey'
```

EarlGrey is the poolable test component

**Comment by saltares** [comment]
@meisterfuu, could you please try replicate with 1.7.2?

**Comment by meisterfuu** [comment]
Okay. But I don't know if I can do so before monday.

**Comment by meisterfuu** [comment]
I had some time and created a new demo project. (https://github.com/meisterfuu/AshleyGwtTest)
Same result with 1.7.2 

If I replace the PooledEngine with an Engine it works.

**Comment by saltares** [comment]
Just cloned the repository and, after importing the Gradle project, I'm getting: `00:00:00.003 [ERROR] Unable to find 'MyGdxGame.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?`

**Comment by meisterfuu** [comment]
Weird. I just created the project with the gdx installer tool and added component class etc. Is something missing in the repo maybe? It definetly works for me with a not pooled engine and `gradlew html:superDev`

**Comment by saltares** [comment]
Okay, my Eclipse setup must be borked. Running `gradlew html:superDev` worked. I realised you were missing this in your `MyGdxGame.gwt.xml` file.

```
<extend-configuration-property name="gdx.reflect.include" value="com.mygdx.game" />
```

That tells the reflection API to include the classes in that package for GWT.  Using that, I could run the project, no problem.

**Comment by saltares** [comment]
I added a [gwt support section](https://github.com/libgdx/ashley/wiki/Efficient-Entity-Systems-with-pooling#reflection-and-gwt) to the `PooledEngine` page in the wiki.
