### ISSUE TITLE
Retrieving PooledEngine from EntitySystem

### ISSUE THREAD

**Issue by sonirico** [libgdx/ashley#225]
I am currently using ashley as the ECS engine of my desktop game. Since it is a shoot em up one, I decided that PooledEngine comes handy. I have a PlayableCharacterSystem class which manages the user input in order to know when to move or open fire. In the latter case, I need to retrieve the pooled engine through the method getEngine so as to add new entities with the createEntity method, as explained in the documentation. The problem is, getEngine returns a reference to the Engine class, which has no available createEntity method, needed to use pools. 

I thought in adding a reference in my EntitySystem class pointing to the main PooledEngine created in my GameScreen class and then initialized in its constructor, however that doesn't feel right at all. Is there any simpler approach?

**Comment by saltares** [comment]
I've been working on adding serialization support for Ashley and, in order to do that, I needed `Engine` to support something similar. I added this on the `serialization` branch.

https://github.com/libgdx/ashley/blob/serialization/ashley/src/com/badlogic/ashley/core/Engine.java#L55

Yo help you out, I could just add that in the main branch. After that gets merged you'd be able to get it from the next snapshot.

I think that's a much cleaner solution.

**Comment by sonirico** [comment]
Great. For now I think I will be using a WeaponFactory or something similar to encapsulate that reference to the PooledEngine object into a class more wide accessible than just a subclassed entity system.

**Comment by laubed** [comment]
couln't you just cast the Engine reference from getEngine() to PooledEngine?
`PooledEngine myEngine = (PooledEngine)getEngine();`

**Comment by sonirico** [comment]
That's another possibility, indeed. But isn't casting supposed to be an as expensive as avoidable operation? Given the fact that firing bullets is going to be a very common task, might it affect performance negatively? Either way, I consider the solution proposed by @saltares much more elegant.

**Comment by laubed** [comment]
Of couse it is more elegant but it requires you to modify the library codebase. My solution is meant to be a quick fix for your problem. @saltares could you also merge in my PR?

**Comment by saltares** [comment]
Casting is the easiest workaround for now, until I add that `createEntity()` method to `Engine`. Will try to get around to that this weekend.

@laubed PR merged.

**Comment by saltares** [comment]
Added in #227.
