### ISSUE TITLE
Question: How to serialize entities with components?

### ISSUE THREAD

**Issue by sonirico** [libgdx/ashley#228]
In order to set up the levels and spawning enemies on my beat'em up game, I have to create entities and components. Since a single entity can be made up with a lot of components, I decided that I should create them manually, and then serialize them to a file which I will be using to load the stage. I tried to use the Gdx Json utility, however I am getting and stackoverflowerror because of circular dependency. I think that serializing would be the best approach. Would I have to create or extend my own serializer for this? Might it be another way which I am missing?

**Comment by saltares** [comment]
I'm trying to figure that out in the [`serializer`](https://github.com/libgdx/ashley/tree/serialization) branch. I have something basic going on but it doesn't handle component and entity references properly.

**Comment by agrock86** [comment]
I'm facing the same stackoverflow error, and noticed that it just happens when using engine.createEntity() instead of new Entity(). Since it's a pooled engine, it has sense to use createEntity(). Any guidance on how to avoid this error?

**Comment by sonirico** [comment]
@agrock86 You can -temporary, at least- migrate your code to [artemis-odb](https://github.com/junkdog/artemis-odb/). Like ashley, it's an ECS system which currently support serialization quite well.
