### ISSUE TITLE
Add a mechanism to temporarily disable components

### ISSUE THREAD

**Issue by xSke** [libgdx/ashley#229]
In many cases it can be useful to disable a component without removing it. Say you wanted your player to be invisible, so you remove their `SpriteComponent`. Then, you have to keep track of the old sprite and add it back as needed. It would be much easier to just have a `entity.disableComponent(SpriteComponent.class);`, which would make systems ignore that component as if it wasn't there, but you can easily enable it again.

**Comment by saltares** [comment]
That could just be a property in the `SpriteComponent` or a new `VisibilityComponent`.

**Comment by sonirico** [comment]
You could even create an ActorComponent with an scene2d.Actor object and take advantage of the Actor.setVisible and Actor.isVisible functions. Plus, that class also wraps a lot of common used variables.

**Comment by saltares** [comment]
I think we can close this one for now.
