### ISSUE TITLE
How to disable processing of system to specific system only?

### ISSUE THREAD

**Issue by ronjunelopez** [libgdx/ashley#233]
Let say I got movement system and physics system. On my `PlayerSystem`, I want to disable processing of `MovementSystem` on `PlayerSystem` only. Then my `PhysicsSystem` can now freely use the `MovementComponent`. `MovementComponent `is used in `MovementSystem `to increment the `Vector2` position of `TransformComponent`

**Comment by saltares** [comment]
You can just do:

```java
public class PlayerSystem extends EntitySystem {
    public void update(float deltaTime) {
        // ...
        getEngine().getSystem(MovementSystem.class).setProcessing(false);
        // ...
    }
}
````
