### ISSUE TITLE
How do you handle Entity relationship?

### ISSUE THREAD

**Issue by ronjunelopez** [libgdx/ashley#238]
I'm having trouble having entity relationship, like in an RPG. My health-bar consists of 2 texture, a background and a bar. So ended up creating 2 entities, a `Entity healthBackground` and `Entity healthBar`. To attach them to a character or a player, my solution is to create a `AttachmentComponent` or a `OwnershipComponent` or whatever you call them, just to store its parent. I need some advise or opinion from you guys, because I don't know if it's the sufficient way to handle this relationship.

**Comment by MrRamych** [comment]
You need just to create `Entity healthBar`, then add `HealthBarComponent implements Component` which stores needed all needed data like textures
