### ISSUE TITLE
How to "init" later added components?

### ISSUE THREAD

**Issue by MarcManhart** [libgdx/ashley#239]
Hi,
(I like your work. Its a great System by the way :) )
Ive got a question in udnerstanding your idea. Ive got a System like that:

```
public class ScriptSystem extends EntitySystem {

	private ImmutableArray<Entity> entities;

	private ComponentMapper<ScriptComponent> sm = ComponentMapper.getFor(ScriptComponent.class);

	public void addedToEngine(Engine engine) {
		this.entities = engine.getEntitiesFor(Family.all(ScriptComponent.class).get());
	}

	public void update(float deltaTime) {
		for (int i = 0; i < this.entities.size(); i++) {
			Entity entity = this.entities.get(i);
			ScriptComponent scriptComponent = sm.get(entity);
			for (Script script : scriptComponent.scripts) {
				script.update(deltaTime);
			}
		}
	}
}

```

So Ive got two Problems: How can I implement an init()-Method which calls only once, when the component is added and the system is already processing? Maybe I want add a component while runtime and therefore the system has to call init on that specific component automaticaly.

Ive tried to understand aschleys internals but im a little bit confused:
Im getting all the entities for the system in the `addedToEngine`-Method in the example from above. The strange thing is that this Method is never called again (also not if I add some entities with relevant components later) but the system still works and seems to recognize the changes since the update-method will also deal with later added entities. How could that be? :D 

Thanks for your help in advance!

**Comment by meisterfuu** [comment]
Ashley keeps track of the ImmutableArray and updates those according to the family. You can register a listener on the engine, that gets called when an entity is added.

**Comment by MrRamych** [comment]
Do something like this:
```java
public class ScriptSystem extends EntitySystem implements EntityListener {

    private Array<Entity> entities = new Array<>();

    private ComponentMapper<ScriptComponent> sm = ComponentMapper.getFor(ScriptComponent.class);

    public void update(float deltaTime) {
        for (int i = 0; i < this.entities.size(); i++) {
            Entity entity = this.entities.get(i);
            ScriptComponent scriptComponent = sm.get(entity);
            for (Script script : scriptComponent.scripts) {
                script.update(deltaTime);
            }
        }
    }

    entityAdded(Entity entity) {
        entities.add(entity);
    }

    entityRemoved(Entity entity) {
        entities.remove(entity, true);
    }

}
```

And add this it to engine like this:
```java
ScriptSystem scriptSystem = new ScriptSystem();
engine.addSystem(scriptSystem);
engine.addEntityListener(Family.all(ScriptComponent.class).get(), scriptSystem);
```
