### ISSUE TITLE
How to find an entitiy by id?

### ISSUE THREAD

**Issue by MarcManhart** [libgdx/ashley#240]
I'm wondering how to access central game-related properties like game-state and so on from any System.

My approach is to create a Entity without any visual components or something similar but just with one script-component, so all my general game/map/etc ... logic can be playced there. However I have no idea, how to access this entity than from an _EntitySystem_. Is there a posiblility to give an entity an unique id and then _"find"_ it (like` findEntityByID(...)`)?

Maybe its not a good approach to store all the general stuff into an entity itself (I was just inspired by Unity3D Tutorials)?

**Comment by saltares** [comment]
Ashley doesn't give support for entity ids out of the box. Instead, you can easily add an IDSystem to the engine that does what you want.

This is because some games may have special requirements here, ie. networking.

**Comment by MarcManhart** [comment]
Can you please explain what do you mean with the IDSystem? I mean how shold this looks like?
The idea of entities that holds an ID is to access this entity at any point by this ID when needed. A System however works isolated and doing its own stuff. So I'm a little bit confused about that.

**Comment by laubed** [comment]
I would implement an entitylistener that keeps a map <Integer, Entity> and another map <Entity, Integer>.
The addedToEngine and removedFrom engine (don't know the exacr method names right now) populate these maps.
