### ISSUE TITLE
Ashley Standalone?

### ISSUE THREAD

**Issue by Favorlock** [libgdx/ashley#242]
I noticed that Ashley has a hard dependency on GDX. Would really love to see this as a standalone library so that it could be utilized in other existing environments.

**Comment by saltares** [comment]
We ony use Libgdx's containers, you can very well use Ashley with any other environment you want. This is at the top of the README page.

> Ashley lives under the Libgdx family but it does not force you to use that specific framework if you do not wish to do so.

The Libgdx team thought about factoring the container library out but decided not to do it in the end.
