### ISSUE TITLE
Feature Request: Name-Property for entities

### ISSUE THREAD

**Issue by iaavo** [libgdx/ashley#249]
I would love to see setName() and getName() for the Entity-Class. The toString() method should then also show the name of the entity. This would aid greatly in debugging.

**Comment by saltares** [comment]
You can always have a `NameComponent` and a `NameSystem` to retrieve entities by name or similar. I believe this is project specific and I want to keep Ashley as small as possible.

**Comment by iaavo** [comment]
Maybe I didn't make myself clear enough. 
I want to override the toString() method of Entity purely for debugging purposes. Eclipse debugger always uses the toString() method which by default is non meaningful. 

I don't want to retrieve entities by name or something but to print its purpose in a human readable format. 

So I don't think this is project specific at all. It would greatly help in identifying which entity currently is being debugged. Right now I have to tediously look through its components and check their state to deduce which entity it is. 

Now that I think about it, instead of having setName(), a better solution would be to provide some kind of entity name formatter interface to entities, which in turn can fetch its components for dynamic name formatting. So it would be nice to have setNameFormatter(IEntityNameFormatter) in the API of the Entity class.

**Comment by laubed** [comment]
Perhaps implementing a way to specify the entity class for the EntitySystem/PooledEntitySystem to make it generic. That way you could also implement your own entity class that you could extend to meet your requirements.
BUT: that would somehow damage the architecture of the entity system. 

A better idea would be a NameComponent and some kind of log(message,entity) method that generates a message out of the NameComponent and message

Am 28. Oktober 2016 21:58:34 MESZ, schrieb Albert Flaig <notifications@github.com>:

**Comment by junkdog** [comment]
> Eclipse debugger always uses the toString() method which by default is non meaningful.

Since you're using eclipse - have you considered eclipse's "Detail Formatters"? A pretty nice write-up on how to do it here: http://codepoke.net/2014/09/24/libgdx-debug-tips-n-tricks/ - it should be easy to adapt for ashley.

Otherwise, may I recommend a writing a `DebugUtil` class? It's not ideal, but evaluating `DebugUtil.toString(entity)` is pretty straightforward.

**Comment by iaavo** [comment]
Thanks for the suggestion @junkdog. Eclipse Detail Formatter indeed works as a workaround for my use case. I just hoped I could get around using it, as it does not persist within the source code and as such cannot be committed into version control. 

@laubed Yes, I also tried to implement my own entity class and I also tried to make a wrapper class for entities, but the entity class is too tightly coupled with the Engine to make it possible. I also cloned ashley, integrated it into my build system and modified the entity class to my needs. However, I then had trouble getting it to work for the html build, as it was missing source files and no matter what I changed in the _gwt.gwt.xml file, nothing worked. 

As an example here is my use case: I try to debug my `RenderingSystem` which is a `IteratingSystem` and loops through each entity. I have a lot of entities and need to find the exact moment when a specific entity is being processed. However most entities do have the same components and vary only little in state. It would be trivial to find it if could assign each entity a name formatter to print e.g "Block@(x,y)". If I used some kind of `NameComponent` along `NameSystem`, my logging would be flooded with entity names, as the `RenderingSystem` iterates through all entities. Using a `DebugUtil.toString(entity)` does not help much either in this case (at least I cant imagine how). 

I have another suggestion on how to solve it. Right now the entity class has a flags attribute, which is user managed. I have no idea which purpose it might have. So instead of the flags attribute you could replace it with a user object and add some API `setUserObject()` and `getUserObject()`. The `toString()` method of the entity then just delegates to the `userObject.toString()`. Many libraries use the pattern of user objects to carry along meta data to generic classes. Scene2D also uses it, so why not Ashley?

If you still don't see my point of view, then I'll give in and will turn to the use of Eclipse Detail Formatter along with `DebugUtil.toString(entity)` to have the entity name formatting code at least partly in source code.

**Comment by laubed** [comment]
What about adding a DebugComponent and your DebugUtil.toString(entity) only log messages if the entity has the DebugComponent.
The DebugComponent could also include the name to track down bugs.

**Comment by iaavo** [comment]
I dont want to print anything to the log. Only let the Eclipse Debugger show me the name for easy identifying.
