### ISSUE TITLE
Can one component contain others?

### ISSUE THREAD

**Issue by Marty** [libgdx/ashley#258]
Hi,

I was wondering if `Component`s can contain 0-n other components.
For example the component `Car` contains `Drivable` and `Explodes`.

Right now I'm using a mix of inheritance and components (setting multiple components in constructor) which prevents me from using the entity pooling.

**Comment by mgsx-dev** [comment]
IMO your Entity/component design might not be right, here is an example : you have 2 cars which are 2 entities, both have Car component, the first one have Drivable component but not the other one. With this design, player can drive the first one but no the other one.

Please create a topic on stackoverflow if you have any further questions, github bug tracker is not the right place for questions like this.

**Comment by Marty** [comment]
Thanks for your answer, but I don't really understand what you're trying to say.

I just want a "shortcut" so to speak to not have to add all the components that make up a car manually.
For example instead of adding components `Drivable`, `Movable`, `Speed`, `Steering` ... I just want to add `Car`.

Question is (and that's what the "question"-tag is for here): Is it possible somehow without having to use custom entities like I do now (`CarEntity` implements `Entity` and sets all components in its contructor)?

If it is, I will glady create a question on SO and answer it myself, if not, it would be a nice addition to this library and this the right place to address it.

**Comment by mgsx-dev** [comment]
Sorry if you didn't understood me. Why not simply use a method that adds some component to your entity : 
```
public static void makeCar(Entity entity){
  entity.add(new Drivable());
  entity.add(new Movable());
  ... and so on ...
}
```

**Comment by Marty** [comment]
Ok, so it does not provide that kind of feature.
Yes, in that case I maybe should go for something like this. Or implement my own pooling ... I'll see.
Thanks!
