### ISSUE TITLE
Is it possible to get entities by their common interface?

### ISSUE THREAD

**Issue by xahon** [libgdx/ashley#268]
```
interface IMyComponentBase implements Component {}

class Derived1 implements IMyComponentBase {}
class Derived2 implements IMyComponentBase {}

engine.getEntitiesFor(
    Family.all(IMyComponentBase.class).get() // not working
);
```

**Comment by aesophor** [comment]
I have this problem too, It only returns the first entity that matches the specified family.

**Comment by mgsx-dev** [comment]
@xahon you can't do that, components are registered by its concrete class.
and what you want to do is against ECS principle IMO.

**Comment by xahon** [comment]
@mgsx-dev may be you're right. I still haven't stopped thinking in OOP style but right now I can't give you an example for this problem

**Comment by metaphore** [comment]
I'm a bit late to the party, but maybe you will find it useful. Family is a powerful tool, you still can put all required component classes manually under `any` rule and get pretty the same result. If you prefer, a bit of automation could be achieved with reflection.
