### ISSUE TITLE
Porting Ashley to Kotlin

### ISSUE THREAD

**Issue by adam-arold** [libgdx/ashley#271]
Hi there. I'm planning to port Ashley to [Kotlin](https://github.com/Hexworks/amethyst). I'm opening this issue to clarify my intent. I'm also using the Apache 2 license and the project will be open source. Is this OK with you? Do you want me to do anything else apart from putting links to this project?

**Comment by crykn** [comment]
Hey @adam-arold, that sounds like an interesting project. Did anything ever come of your intentions? Regarding the licensing: you just have to comply with the conditions stated [here](https://github.com/libgdx/ashley/blob/master/LICENSE); see the top of the page for a quick summary. For future questions like this, our [Discord](https://libgdx.com/community/discord/) server would probably be a better place.

**Comment by adam-arold** [comment]
Hi, @crykn ! I ended up rolling my own implementation as Kotlin has some different constructs that are not present in Java and it made sense to just re-design the whole thing. Thanks for the support! 👍
