### ISSUE TITLE
IteratingSystem before/after processing

### ISSUE THREAD

**Issue by benediktviebahn** [libgdx/ashley#273]
I just came accross [this issue](https://github.com/libgdx/ashley/issues/208) after wondering how to do something before and after entities are being processed. 
This is the solution:

```
@Override
    public void update(float deltaTime) {
        camera.update();

        batch.begin();

        batch.setProjectionMatrix(camera.combined);
        super.update(deltaTime);
        batch.end();
    }
```
It works, but it's not very intuitive because you have to know the implementation of IteratingSystem.update(...) and that it's just calling processEntity for each entity. I think before/after hooks for the processEntity method would be nicer.

**Comment by mgsx-dev** [comment]
overriding update method to add some pre/post process is very common. Adding some hooks would over-complexify things for no reason.
