### ISSUE TITLE
Kotlin coroutine support

### ISSUE THREAD

**Issue by ronjunevaldoz** [libgdx/ashley#283]
Everything now is using kotlin+coroutine, which we could concurrently execute process.

**Comment by mgsx-dev** [comment]
Ashley is not thread safe and no plan to migrate to kotlin. You can implement some multi threading system in your code if needed but that's a highly edge case.

**Comment by cypherdare** [comment]
You might be interested in the [Ktx async](https://github.com/libktx/ktx/tree/master/async) library, which provides coroutine support for libGDX. It allows coroutines to be used for asynchronous tasks and provides a main game thread dispatcher. There are no plans to convert any of libGDX to Kotlin, as that would break GWT and RoboVM compatibility, and I don't think the team wants to take on maintenance of Kotlin extensions.
