### ISSUE TITLE
Make removed flag of entity accesable

### ISSUE THREAD

**Issue by Quillraven** [libgdx/ashley#284]
Hi,

in all of my projects I am using box2d together with Ashley and every time there is some issue in box2d ContactListener with removed entities.

I tried out several helper methods to find out if the callback is coming from a removed entity but it seems like the behavior is not consistent.

I am using a PooledEngine and sometimes the "isScheduledForRemoval" is set to true, sometimes the entity has no more components but sometimes none of the above is true.

I noticed in the debugger that there is a "remove" flag in the entity which I guess is set when it gets removed from the engine?

But this flag is not accessible. 

Can we change that please or is there a proper solution to identify entities that get removed from the engine?

Is this project even maintained anymore? I can provide a PR if someone tells me that it is worth it and a new release will be available with the fix.

**Comment by Quillraven** [comment]
@dsaltares are you still there?

**Comment by dsaltares** [comment]
Hi @Quillraven. Thanks for sending the issue and sorry for the delay. I am not actively maintaining this project anymore. Would you be able to work with a modified fork?

**Comment by Quillraven** [comment]
Thanks for the response. I know how to fork and make a PR but who would merge it and release a new version? Would you do that?

**Comment by mgsx-dev** [comment]
fixed by #285
