### ISSUE TITLE
Ashley should not let you add multiple of the same component to an entity

### ISSUE THREAD

**Issue by thechubbypanda** [libgdx/ashley#287]
Since there's no way to get all the components of a single type from an entity, I assume it's not supported.

**Comment by thechubbypanda** [comment]
The same goes for systems, I believe

**Comment by Quillraven** [comment]
it already does that. when you add a component of the same type then the old instance gets replaced with the new one.

at least for a pooledengine.

**Comment by mgsx-dev** [comment]
this is an [intended behavior](https://github.com/libgdx/ashley/blob/master/ashley/src/com/badlogic/ashley/core/Entity.java#L61) (for all engines), please close.

**Comment by thechubbypanda** [comment]
My bad
