### ISSUE TITLE
Unable to access hasComponent method on Entity

### ISSUE THREAD

**Issue by Blunderchips** [libgdx/ashley#290]
Access on [hasComponent](https://github.com/libgdx/ashley/blob/master/ashley/src/com/badlogic/ashley/core/Entity.java#L155) method on `Entity` class has been left as default (protected) leaving it inaccessible. There is no reason for this method to be protected as it is already directly accessible using a [ComponentMapper](https://github.com/libgdx/ashley/blob/master/ashley/src/com/badlogic/ashley/core/ComponentMapper.java#L42). 

I require a quick and easy way to determine whether a given `Entity` has a certain `Component`(s) without needing to declare a new `ComponentMappers` for the sole purpose of calling `hasComponent`.

Ashley version: `1.8.2`

**Comment by mgsx-dev** [comment]
hasComponent takes a ComponentType object as argument, not a Component class. And open this method would bypass component mapper concept (which is recommended for good performance).
what you can do is : `entity.getComponent(...) != null` which cover your use case.

**Comment by Blunderchips** [comment]
Ok, thank you
