### ISSUE TITLE
how is the compent managed in memory? 

### ISSUE THREAD

**Issue by choxsword** [libgdx/ashley#291]
the reason ECS (entity component system) has great performance, like entitas in unity, is that components of same type are put in the same memory chunk, which make component iterating fast and efficient.

However, in java we cannot manage object memory location, so ecs seems to be not so useful as c++ in java language.  Does **ashley** handled this problem?

**Comment by dsaltares** [comment]
Ashley is meant to be super simple and does not attempt to allocate contiguous memory blocks for components. Other Java ECS implementations are faster atm as well. However, Ashley is quite easy to use.

Hope this answers your question.
