### ISSUE TITLE
"Getting Started" guide uses deprecated Gradle syntax

### ISSUE THREAD

**Issue by carlislefox** [libgdx/ashley#309]
Hiho,

https://github.com/libgdx/ashley/wiki/Getting-started-with-Ashley

Lists gradle inclusion as:

` dependencies {
        compile "com.badlogicgames.ashley:ashley:1.7.3"
    }`

However the syntax should be:

` dependencies {
        implementation "com.badlogicgames.ashley:ashley:1.7.4"
    }`

Fhox

**Comment by crykn** [comment]
Fixed.
